using System;
using System.Collections.Generic;

// Token: 0x020005E4 RID: 1508
internal sealed class Class725
{
	// Token: 0x04001954 RID: 6484
	public static List<string> list_0 = new List<string>
	{
		"VALORANT-Win64-Shipping",
		"csgo",
		"cs2",
		"minecraft",
		"ktane",
		"TOXIKK",
		"dirt3_game",
		"FullMojo",
		"eurotrucks2",
		"DungeonSouls",
		"Hero_Siege",
		"WizardWarsLauncher",
		"quakelive_steam",
		"sir",
		"SpeedRunners",
		"starbound",
		"starbound_opengl",
		"TabletopSimulator",
		"toribash",
		"Unturned",
		"aces",
		"arma2",
		"ArmA2OA",
		"arma3",
		"maniaplanet",
		"broforce_beta",
		"HeroesAndGeneralsDesktop",
		"hng",
		"downwell",
		"RebelGalaxy",
		"RebelGalaxyGOG",
		"vermintide",
		"Star_Trek_Online",
		"Scrivener",
		"Scrivener",
		"Atilla",
		"Bastion",
		"BloodBowl2",
		"BloodBowl2_DX_32",
		"BloodBowl2_GL_32",
		"Borderlands",
		"Borderlands2",
		"Brothers",
		"Cities",
		"Darkest",
		"Darksiders2",
		"defcon",
		"DMC-DevilMayCry",
		"dontstarve",
		"DotP_D14",
		"GTAIV",
		"DragonAgeInquisition",
		"DungeonoftheEndless",
		"DustAET",
		"DwarfFortress",
		"DXHRDC",
		"ed6_win",
		"EndlessLegend",
		"eu4",
		"FTLGame",
		"GalCiv2",
		"GeometryWars",
		"HexcellsPlus",
		"Hexcells",
		"HotlineGL",
		"HotlineMiami",
		"Kingdom",
		"KSP",
		"MetroLL",
		"MKKE",
		"MKKE",
		"PAC-MAN",
		"payday2_win32_release",
		"PlanetSide2_x64",
		"Polynomial",
		"PrisonArchitect",
		"ProjectZomboid",
		"ReallyBigSky",
		"ReassemblyRelease",
		"RebelGalaxyGOG",
		"RebelGalaxySteam",
		"reprisaluniverse",
		"Reus",
		"Rome2",
		"SanctumGame-Win32-Shipping",
		"Scribble",
		"Se4",
		"sh4",
		"sh4",
		"sh4",
		"ShooterGame",
		"SinsofaSolarEmpireRebellion",
		"SkullGirls",
		"sots2",
		"SpaceChem",
		"StarDrive",
		"starwarsbattlefront",
		"SunlessSea",
		"superhexagon",
		"SuperMeatBoy",
		"Terraria",
		"TheyBleedPixelsPC",
		"Timberman",
		"TombRaider",
		"Torchlight2",
		"Torchlight2",
		"Trine2_32bit",
		"UNDERTALE",
		"uplink",
		"v2game",
		"Waves",
		"Wildstar",
		"Windward",
		"WL2",
		"WorldOfGoo",
		"X3AP",
		"X3AP_n",
		"X3TC",
		"XRebirth",
		"yso_win",
		"Zigfrak",
		"Ziggurat",
		"TmUnitedForever",
		"EDLaunch",
		"THUG",
		"UE4-Win64-Test",
		"TalesofZestiria",
		"TalesofZestiria",
		"AIWar",
		"Application-x64",
		"Audiosurf2",
		"Gnomoria",
		"NEOScavenger",
		"oolite",
		"Overture",
		"Pandora",
		"sspace",
		"SublevelZero",
		"Tidalis",
		"X-Plane-32bit",
		"X-Plane",
		"WAR",
		"RobloxPlayerBeta",
		"RobloxStudioBeta",
		"fortnite",
		"r5apex",
		"Subnautica",
		"Subnautica32",
		"Brawlhalla",
		"ScrapMechanic",
		"VRChat",
		"Paladins",
		"SoTGame",
		"Europa_Client",
		"RainbowSix",
		"RainbowSix_Vulkan",
		"RainbowSix_BE",
		"GTA5",
		"TslGame",
		"hl",
		"hl2",
		"left4dead",
		"left4dead2",
		"gta_sa",
		"FortniteClient-Win64-Shipping",
		"LEGOHobbit",
		"SPEED2",
		"Terraria",
		"bf1",
		"bf2",
		"bf3",
		"bf4",
		"Raft",
		"ForzaHorizon4",
		"Insurgency",
		"Titanfall2",
		"RustClient",
		"RainbowSix",
		"RainbowSix_Vulkan",
		"ScrapMechanic",
		"TheForest",
		"Javaw",
		"DueProcess",
		"t6mp",
		"teardown",
		"Control",
		"League of Legends",
		"DayZ",
		"forest",
		"Multi Theft Auto",
		"gta_sa",
		"prototype2",
		"Back4Blood",
		"ConanSandbox",
		"DeadIslandGame",
		"DeadIslandRiptideGame",
		"DyingLightGame",
		"FarCry5",
		"bf5",
		"bfv",
		"DyingLightGame_x64_rwdi",
		"wotblitz",
		"WorldOfWarships64",
		"Asphalt9_Steam_x64_rtl",
		"DOOMx64",
		"Doom3",
		"DOOMEternalx64vk",
		"Frostpunk",
		"SkyrimSE",
		"wgcs_api",
		"wotblitz"
	};

	// Token: 0x04001955 RID: 6485
	public static List<string> list_1 = new List<string>
	{
		"VALORANT-Win64-Shipping.exe",
		"csgo.exe",
		"minecraft.exe",
		"ktane.exe",
		"TOXIKK.exe",
		"dirt3_game.exe",
		"FullMojo.exe",
		"eurotrucks2.exe",
		"DungeonSouls.exe",
		"Hero_Siege.exe",
		"WizardWarsLauncher.exe",
		"quakelive_steam.exe",
		"sir.exe",
		"SpeedRunners.exe",
		"starbound.exe",
		"starbound_opengl.exe",
		"TabletopSimulator.exe",
		"toribash.exe",
		"Unturned.exe",
		"aces.exe",
		"arma2.exe",
		"ArmA2OA.exe",
		"arma3.exe",
		"maniaplanet.exe",
		"broforce_beta.exe",
		"HeroesAndGeneralsDesktop.exe",
		"hng.exe",
		"downwell.exe",
		"RebelGalaxy.exe",
		"RebelGalaxyGOG.exe",
		"vermintide.exe",
		"Star_Trek_Online.exe",
		"Scrivener.exe",
		"Scrivener.exe",
		"Atilla.exe",
		"Bastion.exe",
		"BloodBowl2.exe",
		"BloodBowl2_DX_32.exe",
		"BloodBowl2_GL_32.exe",
		"Borderlands.exe",
		"Borderlands2.exe",
		"Brothers.exe",
		"Cities.exe",
		"Darkest.exe",
		"Darksiders2.exe",
		"defcon.exe",
		"DMC-DevilMayCry.exe",
		"dontstarve.exe",
		"DotP_D14.exe",
		"GTAIV.exe",
		"DragonAgeInquisition.exe",
		"DungeonoftheEndless.exe",
		"DustAET.exe",
		"DwarfFortress.exe",
		"DXHRDC.exe",
		"ed6_win.exe",
		"EndlessLegend.exe",
		"eu4.exe",
		"FTLGame.exe",
		"GalCiv2.exe",
		"GeometryWars.exe",
		"HexcellsPlus.exe",
		"Hexcells.exe",
		"HotlineGL.exe",
		"HotlineMiami.exe",
		"Kingdom.exe",
		"KSP.exe",
		"MetroLL.exe",
		"MKKE.exe",
		"MKKE.exe",
		"PAC-MAN.exe",
		"payday2_win32_release.exe",
		"PlanetSide2_x64.exe",
		"Polynomial.exe",
		"PrisonArchitect.exe",
		"ProjectZomboid.exe",
		"ReallyBigSky.exe",
		"ReassemblyRelease.exe",
		"RebelGalaxyGOG.exe",
		"RebelGalaxySteam.exe",
		"reprisaluniverse.exe",
		"Reus.exe",
		"Rome2.exe",
		"SanctumGame-Win32-Shipping.exe",
		"Scribble.exe",
		"Se4.exe",
		"sh4.exe",
		"sh4.exe",
		"sh4.exe",
		"ShooterGame.exe",
		"SinsofaSolarEmpireRebellion.exe",
		"SkullGirls.exe",
		"sots2.exe",
		"SpaceChem.exe",
		"StarDrive.exe",
		"starwarsbattlefront.exe",
		"SunlessSea.exe",
		"superhexagon.exe",
		"SuperMeatBoy.exe",
		"Terraria.exe",
		"TheyBleedPixelsPC.exe",
		"Timberman.exe",
		"TombRaider.exe",
		"Torchlight2.exe",
		"Torchlight2.exe",
		"Trine2_32bit.exe",
		"UNDERTALE.exe",
		"uplink.exe",
		"v2game.exe",
		"Waves.exe",
		"Wildstar.exe",
		"Windward.exe",
		"WL2.exe",
		"WorldOfGoo.exe",
		"X3AP.exe",
		"X3AP_n.exe",
		"X3TC.exe",
		"XRebirth.exe",
		"yso_win.exe",
		"Zigfrak.exe",
		"Ziggurat.exe",
		"TmUnitedForever.exe",
		"EDLaunch.exe",
		"THUG.exe",
		"UE4-Win64-Test.exe",
		"TalesofZestiria.exe",
		"TalesofZestiria.exe",
		"AIWar.exe",
		"Application-x64.exe",
		"Audiosurf2.exe",
		"Gnomoria.exe",
		"NEOScavenger.exe",
		"oolite.exe",
		"Overture.exe",
		"Pandora.exe",
		"sspace.exe",
		"SublevelZero.exe",
		"Tidalis.exe",
		"X-Plane-32bit.exe",
		"X-Plane.exe",
		"WAR.exe",
		"RobloxPlayerBeta.exe",
		"RobloxStudioBeta.exe",
		"fortnite.exe",
		"r5apex.exe",
		"Subnautica.exe",
		"Subnautica32.exe",
		"Brawlhalla.exe",
		"ScrapMechanic.exe",
		"VRChat.exe",
		"Paladins.exe",
		"SoTGame.exe",
		"Europa_Client.exe",
		"RainbowSix.exe",
		"RainbowSix_Vulkan.exe",
		"RainbowSix_BE.exe",
		"GTA5.exe",
		"TslGame.exe",
		"hl.exe",
		"hl2.exe",
		"left4dead.exe",
		"left4dead2.exe",
		"gta_sa.exe",
		"FortniteClient-Win64-Shipping.exe",
		"LEGOHobbit.exe",
		"SPEED2.EXE",
		"Terraria.exe",
		"bf1.exe",
		"bf2.exe",
		"bf3.exe",
		"bf4.exe",
		"Raft.exe",
		"ForzaHorizon4.exe",
		"Insurgency.exe",
		"Titanfall2.exe",
		"RustClient.exe",
		"RainbowSix.exe",
		"RainbowSix_Vulkan.exe",
		"ScrapMechanic.exe",
		"TheForest.exe",
		"Javaw.exe",
		"DueProcess.exe",
		"t6mp.exe",
		"teardown.exe",
		"Control.exe",
		"League of Legends.exe",
		"DayZ.exe",
		"forest.exe",
		"Multi Theft Auto.exe",
		"gta_sa.exe",
		"prototype2.exe",
		"Back4Blood.exe",
		"ConanSandbox.exe",
		"DeadIslandGame.exe",
		"DeadIslandRiptideGame.exe",
		"DyingLightGame.exe",
		"FarCry5.exe",
		"bf5.exe",
		"bfv.exe",
		"DyingLightGame_x64_rwdi.exe",
		"wotblitz.exe",
		"WorldOfWarships64.exe",
		"Asphalt9_Steam_x64_rtl.exe",
		"DOOMx64.exe",
		"Doom3.exe",
		"DOOMEternalx64vk.exe",
		"Frostpunk.exe",
		"SkyrimSE.exe",
		"wgcs_api.exe",
		"wotblitz.exe"
	};

	// Token: 0x04001956 RID: 6486
	public static List<string> list_2 = new List<string>
	{
		"csrss",
		"Sendevsvc",
		"svchost",
		"wlanext",
		"TextInputHost",
		"explorer",
		"SearchApp",
		"vgtray",
		"wininit",
		"WUDFHost",
		"taskhostw",
		"fontdrvhost",
		"RuntimeBroker",
		"conhost",
		"lsass",
		"Registry",
		"ShellExperienceHost",
		"sihost",
		"StartMenuExperienceHost",
		"dwm",
		"dllhost",
		"svchost",
		"smss",
		"dasHost",
		"winlogon",
		"System",
		"Idle",
		"audiodg",
		"GameModeX",
		"WmiPrvSE",
		"ApplicationFrameHost",
		"ctfmon",
		"BoosterX"
	};

	// Token: 0x04001957 RID: 6487
	public static List<string> list_3 = new List<string>
	{
		"realtek",
		"killer",
		"intel(r)",
		"qualcomm",
		"tp-link",
		"broadcom",
		"graphics"
	};

	// Token: 0x04001958 RID: 6488
	public static List<string> list_4 = new List<string>
	{
		"Sense",
		"WinDefend",
		"WdNisSvc",
		"R0BoosterX",
		"R0BoosterX(1)",
		"R0BoosterX(2)",
		"R0BoosterX(3)",
		"R0BoosterX(4)",
		"R0WpfSurface"
	};

	// Token: 0x04001959 RID: 6489
	public static List<string> list_5 = new List<string>
	{
		"update",
		"defender",
		"edge",
		"nvtmrep",
		"NvProfile",
		"NvNode",
		"обновл",
		"elevation",
		"AMD Crash Defender Service"
	};

	// Token: 0x0400195A RID: 6490
	public static List<string> list_6 = new List<string>
	{
		"lghub",
		"boosterx",
		"gamemodex"
	};

	// Token: 0x0400195B RID: 6491
	public static List<string> list_7 = new List<string>
	{
		"hid",
		"usb",
		"razer",
		"steelseries",
		"logitech"
	};

	// Token: 0x0400195C RID: 6492
	public static List<string> list_8 = new List<string>
	{
		"host",
		"хост"
	};

	// Token: 0x0400195D RID: 6493
	public static List<string> list_9 = new List<string>
	{
		"Deleted",
		"DeletedAllUserPackages",
		"MovedPackages",
		"Mutable",
		"MutableBackup"
	};

	// Token: 0x0400195E RID: 6494
	public static List<string> list_10 = new List<string>
	{
		"microsoft.windowscommunicationsapps",
		"Microsoft.WindowsCamera",
		"Microsoft.WindowsAlarms",
		"Microsoft.SkypeApp",
		"Microsoft.ZuneVideo",
		"Microsoft.ZuneMusic",
		"Microsoft.YourPhone",
		"Microsoft.WindowsSoundRecorder",
		"Microsoft.WindowsMaps",
		"Microsoft.WindowsFeedbackHub",
		"Microsoft.Wallet",
		"Microsoft.People",
		"Microsoft.Office.OneNote",
		"Microsoft.MSPaint",
		"Microsoft.MicrosoftStickyNotes",
		"Microsoft.MicrosoftSolitaireCollection",
		"Microsoft.MicrosoftOfficeHub",
		"Microsoft.Microsoft3DViewer",
		"Microsoft.Getstarted",
		"Microsoft.GetHelp",
		"Microsoft.BingWeather",
		"Microsoft.Todos",
		"Microsoft.549981C3F5F10"
	};

	// Token: 0x0400195F RID: 6495
	public static List<string> list_11 = new List<string>
	{
		"printAndScannerServices",
		"hypervServices",
		"wifiServices",
		"bluetoothServices",
		"encryptServices",
		"storeServices",
		"microsoftAccountServices",
		"uselessServices",
		"vpnOrProxyServices",
		"virtualRealityServices",
		"localNetworkServices",
		"remoteControlServices",
		"diagnosisServices",
		"archiveAndRestoreWindowsServices",
		"passwordBiometryServices",
		"xboxServices",
		"windowsMediaPlayerServices",
		"themesService",
		"sysmainServices",
		"wisvcService",
		"shellHWDetectionService",
		"WwanSvcService",
		"PcaSvcService",
		"DusmSvcService",
		"defragsvcService",
		"W32TimeService",
		"DeviceAssociationService",
		"DisplayEnhancementService",
		"DsmSvcService",
		"FrameServerService",
		"hidservService",
		"LxpSvcService",
		"smphostService"
	};

	// Token: 0x04001960 RID: 6496
	public static List<string> list_12 = new List<string>
	{
		".net",
		".pow",
		"activex",
		"alljoyn",
		"виртуальн",
		"asphalt",
		"beta-верс",
		"bitlocker",
		"bloody",
		"bluetooth",
		"booster",
		"com+",
		"cortana",
		"directx",
		"directx shader cache",
		"forza horizon",
		"gamebar",
		"ghub",
		"hpet",
		"hyper",
		"ipv6",
		"largesystemcache",
		"lastactivityview",
		"meltdown",
		"account",
		"office",
		"store",
		"virtualization",
		"networkthrottlingindex",
		"onboardmemorymanager",
		"onedrive",
		"pin",
		"power throttling",
		"get-physicaldisk",
		"powerx",
		"proxy",
		"radeon software",
		"razer synapse",
		"remote control",
		"screenshare",
		"sim",
		"smartscreen",
		"smarttv",
		"spectre",
		"steam",
		"store",
		"storex",
		"svchosts.exe",
		"svsvc",
		"sysmain",
		"systemresp",
		"tsx",
		"uac",
		"usb",
		"virtualbox",
		"vmware",
		"vpn",
		"fso",
		"фсо",
		"wi-fi",
		"wi fi",
		"wifi",
		"win shift",
		"win v",
		"win+shift",
		"win+v",
		"win32priorityseparation",
		"media player",
		"киоск",
		"xbox",
		"автозагрузк",
		"автозапуск",
		"автоматическ",
		"автообновлен",
		"акселераци",
		"анализ производительности",
		"анимация показа меню",
		"антивирус",
		"архивац",
		"архивиров",
		"ассоциац",
		"база данных",
		"бесполезные",
		"биометрия",
		"битые сектора",
		"брандмауэр",
		"быстродействие",
		"ваш телефон",
		"ввод-вывод данных",
		"веб-камера",
		"видеокарта",
		"виртуальная реальность",
		"виртуальные машины microsoft",
		"виртуальные рабочие столы",
		"восстановлен",
		"временн",
		"учетную запись",
		"учетная запись",
		"отпечат",
		"пин",
		"распознаван",
		"быстродейств",
		"выпиливан",
		"высокая производительность",
		"высокоточный таймер событий",
		"гибернация",
		"голограммы",
		"группировка служб",
		"датчики на планшете",
		"дефрагментация hdd",
		"дефрагментация жесткого диска",
		"диагностика windows",
		"диагностика системы",
		"дистанционное управление",
		"дополненная реальность",
		"дополнительная расширенная очистка",
		"дополнительные кнопки на устройствах (скрипты)",
		"дополнительные устройства",
		"драйвер",
		"жесткий диск",
		"журнал событий windows",
		"загруженные файлы программ",
		"загрузка языков",
		"защита edge",
		"защита системы",
		"защитник windows",
		"импорт",
		"инсайдерская служба",
		"интернет",
		"использование данных",
		"использование сети в диспетчере задач",
		"исправление обновлений windows",
		"история файлов",
		"карт",
		"клавиатур",
		"кнопка уведомлений",
		"компонент smb1",
		"компьютер",
		"контакты",
		"контроль учетных записей (uac)",
		"uac",
		"кошелек",
		"курсор",
		"кэш эскизов",
		"кэширование файлов в общем доступе",
		"локальная сеть",
		"локальная учетная запись",
		"магазин",
		"максимальная производительность",
		"микро-фризы",
		"монитор стабильности системы",
		"назойливые уведомления защиты",
		"настройка роутера",
		"ночной свет",
		"обновлен",
		"оптимизация доставки",
		"обрезка в кино и тв",
		"общий доступ webdav",
		"ограничение локальной сети",
		"ограничение питан",
		"ограничение прав на запуск программ",
		"онлайн авто-подбор драйверов",
		"онлайн обновление времени",
		"онлайн синхронизация времени",
		"оптимизация ssd",
		"отзывчивые соединен",
		"отключение hpet",
		"отпечаток пальца",
		"офлайн обновления",
		"панель задач",
		"параметр сеть и интернет",
		"пароли",
		"передвижение мыши",
		"перезапуск процессов",
		"планшеты",
		"подключен",
		"полноэкранная оптимизация",
		"прерывание",
		"приложения uwp",
		"приложения из store",
		"принтер",
		"проверка битых секторов hdd",
		"проверка целостности системы",
		"программа предварительной оценки windows",
		"прозрачность",
		"прозрачность windows",
		"производительность",
		"прокси",
		"работа uwp приложений в фоне",
		"расширенный буфер win+v",
		"регулировка яркости монитора через клавиши",
		"сбалансированн",
		"сбор файлов кэша",
		"сглаживание шрифтов",
		"сенсорная клавиатура",
		"скачанные файлы",
		"служб",
		"смарт устройства",
		"смарт-карты",
		"смешанная реальность",
		"совместимость",
		"сопряжение с устройствами",
		"стандартный таймер rtc",
		"старые файлы chkdsk",
		"страница оптимизации",
		"схемы питания",
		"телеметрические службы",
		"трафик",
		"уведомлен",
		"удаленное управление",
		"удаленные uwp-приложения",
		"удаленный доступ по паролю",
		"управление дисковыми пространствами",
		"управление уровнями хранилища для windows server",
		"установка приложений для пк в локальной сети",
		"устройство",
		"файлы антивируса windows",
		"файлы базы данных программы просмотра диагностических данных",
		"файлы журнала установок",
		"файлы индексатора",
		"файлы кэша браузеров",
		"файлы оптимизации доставки",
		"файлы системных ошибок",
		"флэш-память",
		"хронология",
		"чистые драйвера",
		"шифрован",
		"экономия энергии",
		"электропитан",
		"яркость",
		"autorun",
		"auto-update",
		"acceleration",
		"performance analysis",
		"menu display animation",
		"antivirus",
		"archive",
		"associations",
		"database",
		"useless",
		"biometrics",
		"broken sectors",
		"firewall",
		"performance",
		"your phone",
		"data input/output",
		"webcam",
		"video card",
		"virtual reality",
		"microsoft virtual machines",
		"virtual desktops",
		"restored",
		"temporary",
		"account",
		"account",
		"print",
		"pin",
		"recognized",
		"fast action",
		"high performance",
		"high precision event timer",
		"hibernation",
		"holograms",
		"grouping services",
		"sensors on tablet",
		"hdd defragmentation",
		"hard drive defragmentation",
		"windows diagnostics",
		"system diagnostics",
		"remote control",
		"augmented reality",
		"additional advanced cleaning",
		"additional buttons on devices (scripts)",
		"additional devices",
		"driver",
		"hard drive",
		"windows event log",
		"downloaded program files",
		"loaded languages",
		"edge protection",
		"system protection",
		"windows defender",
		"import",
		"insider service",
		"internet",
		"data usage",
		"network usage in task manager",
		"fixing windows updates",
		"file history",
		"maps",
		"keyboards",
		"notification button",
		"smb1 component",
		"computer",
		"contacts",
		"account control",
		"uac",
		"wallet",
		"cursor",
		"thumbnail cache",
		"shared file caching",
		"local network",
		"local account",
		"store",
		"maximum performance",
		"micro-freaks",
		"system stability monitor",
		"annoying security notifications",
		"router setup",
		"night light",
		"updated",
		"delivery optimization",
		"trimming in movies and tv",
		"webdav sharing",
		"local network restriction",
		"power restriction",
		"restriction of rights to run programs",
		"online auto-driver selection",
		"online time update",
		"online time sync",
		"ssd optimization",
		"responsive connections",
		"hpet disable",
		"fingerprint",
		"offline updates",
		"taskbar",
		"network and internet settings",
		"passwords",
		"mouse movements",
		"restart processes",
		"tablets",
		"connected",
		"full-screen optimization",
		"interrupted",
		"uwp apps",
		"apps from store",
		"printer",
		"hdd bit sector check",
		"system integrity check",
		"transparency",
		"transparency",
		"performance",
		"proxy",
		"uwp",
		"extended win+v buffer",
		"monitor brightness adjustment via keys",
		"balanced",
		"cache file collection",
		"font smoothing",
		"touch keyboard",
		"downloaded files",
		"services",
		"smart devices",
		"smart cards",
		"mixed reality",
		"compatibility",
		"device pairing",
		"standard rtc timer",
		"old chkdsk files",
		"optimization page",
		"power schemes",
		"telemetry services",
		"notified",
		"management",
		"disk space management",
		"managing storage levels for windows server",
		"installing pc applications on local network",
		"device",
		"windows antivirus files",
		"diagnostic data viewer database files",
		"setup log files",
		"indexer files",
		"browser cache files",
		"delivery optimization files",
		"system error files",
		"memory",
		"timeline",
		"drivers",
		"encrypt",
		"power",
		"brightness",
		"кіоск",
		"автозавантаження",
		"автозапуск",
		"автоматичний",
		"автооновлення",
		"акселерація",
		"аналіз продуктивності",
		"анімація відображення меню",
		"антивірус",
		"архівація",
		"архівування",
		"асоціація",
		"база даних",
		"непотрібні",
		"біометрія",
		"пошкоджені сектори",
		"брандмауер",
		"швидкодія",
		"ваш телефон",
		"введення-виведення даних",
		"веб-камера",
		"відеокарта",
		"віртуальна реальність",
		"віртуальні машини microsoft",
		"віртуальні робочі столи",
		"відновлення",
		"тимчасові",
		"обліковий запис",
		"облікова запис",
		"відбиток",
		"пін",
		"розпізнавання",
		"швидкодія",
		"випилювання",
		"висока продуктивність",
		"високоточний таймер подій",
		"гібернація",
		"голограми",
		"групування служб",
		"датчики на планшеті",
		"дефрагментація hdd",
		"дефрагментація жорсткого диску",
		"діагностика windows",
		"діагностика системи",
		"дистанційне керування",
		"доповнена реальність",
		"додаткове розширене очищення",
		"додаткові кнопки на пристроях (скрипти)",
		"додаткові пристрої",
		"драйвер",
		"жорсткий диск",
		"журнал подій windows",
		"завантажені файли програм",
		"завантаження мов",
		"захист edge",
		"захист системи",
		"захисник windows",
		"імпорт",
		"інсайдерська служба",
		"інтернет",
		"використання даних",
		"використання мережі в диспетчері завдань",
		"виправлення оновлень windows",
		"історія файлів",
		"карти",
		"клавіатура",
		"кнопка сповіщень",
		"компонент smb1",
		"комп'ютер",
		"контакти",
		"контроль облікових записів (uac)",
		"uac",
		"гаманець",
		"курсор",
		"кеш мініатюр",
		"кешування файлів у загальному доступі",
		"локальна мережа",
		"локальний обліковий запис",
		"магазин",
		"максимальна продуктивність",
		"мікро-зависання",
		"монітор стабільності системи",
		"нав'язливі сповіщення захисту",
		"налаштування роутера",
		"ночне світло",
		"оновлення",
		"оптимізація доставки",
		"обрізка в кіно та тв",
		"загальний доступ webdav",
		"обмеження локальної мережі",
		"обмеження живлення",
		"обмеження прав на запуск програм",
		"онлайн авто-підбір драйверів",
		"онлайн оновлення часу",
		"онлайн синхронізація часу",
		"оптимізація ssd",
		"чутливе з'єднання",
		"відключення hpet",
		"відбиток пальця",
		"офлайн оновлення",
		"панель завдань",
		"параметр мережа та інтернет",
		"паролі",
		"переміщення миші",
		"перезапуск процесів",
		"планшети",
		"підключено",
		"повноекранна оптимізація",
		"перервання",
		"додатки uwp",
		"додатки зі store",
		"принтер",
		"перевірка пошкоджених секторів hdd",
		"перевірка цілісності системи",
		"програма попередньої оцінки windows",
		"прозорість",
		"прозорість windows",
		"продуктивність",
		"проксі",
		"робота uwp додатків у фоні",
		"розширений буфер win+v",
		"регулювання яскравості монітора за допомогою клавіш",
		"збалансований",
		"збір файлів кеша",
		"згладжування шрифтів",
		"сенсорна клавіатура",
		"завантажені файли",
		"служби",
		"розумні пристрої",
		"розумні карти",
		"змішана реальність",
		"сумісність",
		"спарювання з пристроями",
		"стандартний таймер rtc",
		"старі файли chkdsk",
		"сторінка оптимізації",
		"схеми живлення",
		"телеметричні служби",
		"трафік",
		"сповіщення",
		"віддалене керування",
		"видалені uwp-додатки",
		"віддалений доступ за паролем",
		"керування дисковими просторами",
		"керування рівнями сховища для windows server",
		"встановлення додатків для ПК в локальній мережі",
		"пристрій",
		"файли антивіруса windows",
		"файли бази даних програми перегляду діагностичних даних",
		"файли журналу встановлень",
		"файли індексатора",
		"файли кеша браузерів",
		"файли оптимізації доставки",
		"файли системних помилок",
		"флеш-пам'ять",
		"хронологія",
		"чисті драйвери",
		"шифрований",
		"економія енергії",
		"електроживлення",
		"яскравість",
		"згладжування",
		"шрифт"
	};
}
